### PR TITLE
Update to 1.16.5

### PR DESCRIPTION
**Pull request by Ayarkay**
Played around with it on live 1.16.5 client for a few hours without issues.

### CODE REVIEW

**Comment by Nathan22211** [comment]
I think he doesn't support the mod anymore, you're better off building it yourself and bringing the fork to curse and modrinth

**Comment by JackDainzh** [comment]
Either way we must thank this man, cause I tried too updating the resources to 1.16.4 version but it just refused to work for me, this build, however, is a bliss.

**Comment by JackDainzh** [comment]
In all oditty it's just weird to abandon this project which actually takes this little to be updated, trully. Maybe the author was waiting for someone to sponsor it via paypal, I have no idea, but that would've been quite funny.

**Comment by Ayarkay** [comment]
Hey Nathan/Jack, thanks for the replies.
Unfortunately you're correct, I figured it was worth a shot at making a pull request but it's clear the author is working on other projects these days. I'll close the pull request to avoid spamming the author. 
Meanwhile I'll work on my own end of things on either maintaining this codebase or rewriting it from scratch. I'll report back once I have substantive contributions to the project.

**Pull request closed without merging**
